baseurl = "https://example.org/"
languageCode = "en-us"
title = "Sera Sera; It's Love"
theme = "creative"
googleAnalytics = ""

publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Stephanie Acosta"
	description = "Kept in a secret place, guarded by conductive forces, lay a song; only when played to the tune of our story will the journey begin..."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Our own mine; our own radio"

		[params.navigation.links]
			about     = "Us"
			services  = "Accomplishments"
			portfolio = "Adventures"
			contact   = "Write It"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Somewhere;"
		slogan2		 = "Far, far, away"
		subtitle   = "Kept in a secret place, guarded by conductive forces, lay a song; only when played to the tune of our story will our journey begin..."
		buttonText = "Sing with me"


	# About section
	[params.about]
		headline    = "We've got it all!"
		description = "We got what you want, Where you want it"

		[params.about.button]
			text = "Heather &The Fleece"
			link = "https://HeatherAndTheFleece.bandcamp.com"


	# Service section
	[params.services]
		headline = "We've done it all"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Got Smart"
            description = "Believe it or not, prior to this terminal case of learning herpes, we were actually thinking about going somewhere"

        [[params.services.list]]
						icon = "fa-home"
						title = "Moved on Up"
						description = "You can use this theme as is, or you can make changes!"

				[[params.services.list]]
            icon = "fa-calendar-times-o"
            title = "Setting a Date"
            description = "On The 11th day of December in the oh 12th year of our lords second millennium"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "We are full of it! Produced Manufactured and Distributed from our own mines in their own beds"

				[[params.services.list]]
						icon = "fa-child"
						title = "Made with Love"
						description = "We are full of it! Produced Manufactured and Distributed from our own mines in their own beds"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "See what else we have out"

		[params.aside.button]
			text = "Hate Us?"
			link = "http://HateUsCuzTheyAint.Us"

	# Contact section
	[params.contact]
		headline = "Write it down"
		description = "Lay down, let the day fade away. A dream awaits..."
		phone = "123-456-6789"
		email = "On.Fleece@Hotmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
